name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run linter
        run: pnpm lint
        continue-on-error: true
      
      - name: Run integration tests
        run: pnpm test:int
        continue-on-error: true
      
      - name: Run E2E tests
        run: pnpm test:e2e
        continue-on-error: true
        env:
          NODE_ENV: test
          PAYLOAD_SECRET: test-secret_key
      
      - name: SonarQube Scan (SonarCloud)
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}